name: Deploy Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'aayuscribe-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd functions
        npm install --omit=dev

    - name: Zip functions
      run: |
        cd functions
        zip -r ../deploy.zip . -x "*.git*" -x "local.settings.json"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ./deploy.zip
