name: Deploy Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'aayuscribe-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './functions'
  NODE_VERSION: '18.x'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub repo'
      uses: actions/checkout@v3

    - name: 'Setup Node.js environment'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies'
      shell: bash
      run: |
        echo "Moving to functions directory..."
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Installing production dependencies..."
        npm ci --only=production
        echo "Dependencies installed successfully"

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
